// rustybuns build box
//   The desktop host, compiled for Linux, with the token gate off and the
//   port open. Alchemy's Hetzner.Service runs `node <main>` under systemd, so
//   main is a small Node launcher that execs the Bun binary sitting next to it.
//
//   .rustybuns/box/launch.mjs   Node: find the data dir, exec the binary, forward signals
//   .rustybuns/box/<name>       Bun: the compiled host (linux-x64, or linux-arm64 on cax)
//
// The whole directory is the unit root on the server (/opt/<unit>/).

import { mkdir } from "node:fs/promises";
import type { BoxTarget, DesktopOs, RustyBunsConfig } from "./config.ts";
import { buildDesktop } from "./build.ts";

export const BOX_DIR = ".rustybuns/box";

export function boxDefaults(b: BoxTarget) {
  return {
    location: b.location ?? b.region ?? "nbg1",
    serverType: b.serverType ?? "cpx12",
    image: b.image ?? "ubuntu-24.04",
    port: b.port ?? 3000,
    volumeSize: b.volumeSize ?? 10,
  };
}

/** Hetzner's cax* types are Ampere ARM; everything else is x86. */
export function boxArch(serverType: string): DesktopOs {
  return /^cax/i.test(serverType) ? "linux-arm64" : "linux-x64";
}

export function boxLauncher(c: RustyBunsConfig): string {
  const { volumeSize } = boxDefaults(c.targets.box!);
  return `// GENERATED by rustybuns. Hetzner.Service runs this with node under systemd.
// It hands the process to the compiled Bun host next to it.
import { spawn } from "node:child_process";
import { chmodSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const bin = join(here, ${JSON.stringify(c.name)});
chmodSync(bin, 0o755); // the unit zip does not keep the exec bit

async function dataDir() {
  if (process.env.DATA_DIR) return process.env.DATA_DIR;
${volumeSize > 0 ? `  // Hetzner automounts an attached Volume at /mnt/HC_Volume_<id>. It can lag
  // the first boot by a few seconds; never fall back to the root disk, or
  // the data splits across two places.
  for (let i = 0; i < 60; i++) {
    const v = existsSync("/mnt") ? readdirSync("/mnt").find((d) => d.startsWith("HC_Volume_")) : undefined;
    if (v) return join("/mnt", v, ${JSON.stringify(c.name)});
    await new Promise((r) => setTimeout(r, 1000));
  }
  console.error("no Hetzner Volume under /mnt after 60s; set DATA_DIR or check the Volume attachment");
  process.exit(1);` : `  return ${JSON.stringify(`/var/lib/${c.name}`)};`}
}

const child = spawn(bin, process.argv.slice(2), { stdio: "inherit", env: { ...process.env, DATA_DIR: await dataDir() } });
for (const sig of ["SIGTERM", "SIGINT", "SIGHUP"]) process.on(sig, () => child.kill(sig));
child.on("exit", (code, signal) => process.exit(code ?? (signal ? 1 : 0)));
`;
}

/**
 * Compile the box host and write its launcher. Returns the binary path.
 * `target` overrides the server's arch, e.g. your own OS to try the box locally.
 */
export async function buildBox(c: RustyBunsConfig, opts: { target?: string } = {}): Promise<string> {
  if (!c.targets.box) throw new Error("no targets.box in rustybuns.config.ts");
  const { serverType } = boxDefaults(c.targets.box);
  await mkdir(BOX_DIR, { recursive: true });
  const out = await buildDesktop(c, { host: "box", target: opts.target ?? boxArch(serverType), outfile: `${BOX_DIR}/${c.name}` });
  await Bun.write(`${BOX_DIR}/launch.mjs`, boxLauncher(c));
  return out;
}
