// rustybuns build box
//   The desktop host with the token gate off and the port open.
//
//   Hetzner: compiled for Linux. Alchemy's Hetzner.Service runs `node <main>`
//   under systemd, so main is a small Node launcher that execs the Bun binary
//   sitting next to it. The whole directory is the unit root (/opt/<unit>/).
//     .rustybuns/box/launch.mjs   Node: find the data dir, exec the binary, forward signals
//     .rustybuns/box/<name>       Bun: the compiled host (linux-x64, or linux-arm64 on cax)
//
//   Railway: a plain Bun bundle, not a binary. Railway.Service uploads a Docker
//   context capped at 32 MiB, and the Bun runtime alone is ~35 MB gzipped, so
//   the runtime comes from the oven/bun image instead. The directories a binary
//   would embed are copied beside the bundle, where the host looks first.
//     .rustybuns/railway/Dockerfile   FROM oven/bun, run box.js
//     .rustybuns/railway/box.js       the host bundle
//     .rustybuns/railway/<dir>        client build, migrations, mounts (by basename)

import { cp, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { basename, join } from "node:path";
import type { DesktopOs, HetznerBoxTarget, RailwayBoxTarget, RustyBunsConfig } from "./config.ts";
import { buildDesktop, embeddedDirs } from "./build.ts";

export const BOX_DIR = ".rustybuns/box";
export const RAILWAY_DIR = ".rustybuns/railway";
/** Where the Railway Volume mounts; the host's DATA_DIR. */
export const RAILWAY_DATA = "/data";

export function railwayDefaults(b: RailwayBoxTarget) {
  return { region: b.region, port: b.port ?? 3000, volume: b.volume ?? true, sleep: b.sleep ?? true };
}

/** The image the bundle runs on: the Bun that built it, so the two never drift. */
export function railwayDockerfile(bunVersion = Bun.version): string {
  return `# GENERATED by rustybuns. Railway builds this; the bundle beside it is the host.
FROM oven/bun:${bunVersion}-slim
WORKDIR /app
COPY . /app
ENV HOST=0.0.0.0
CMD ["bun", "/app/box.js"]
`;
}

export function boxDefaults(b: HetznerBoxTarget) {
  return {
    location: b.location ?? b.region ?? "nbg1",
    serverType: b.serverType ?? "cpx12",
    image: b.image ?? "ubuntu-24.04",
    port: b.port ?? 3000,
    volumeSize: b.volumeSize ?? 10,
  };
}

/** Hetzner's cax* types are Ampere ARM; everything else is x86. */
export function boxArch(serverType: string): DesktopOs {
  return /^cax/i.test(serverType) ? "linux-arm64" : "linux-x64";
}

export function boxLauncher(c: RustyBunsConfig): string {
  const { volumeSize } = boxDefaults(c.targets.box as HetznerBoxTarget);
  return `// GENERATED by rustybuns. Hetzner.Service runs this with node under systemd.
// It hands the process to the compiled Bun host next to it.
import { spawn } from "node:child_process";
import { chmodSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const bin = join(here, ${JSON.stringify(c.name)});
chmodSync(bin, 0o755); // the unit zip does not keep the exec bit

async function dataDir() {
  if (process.env.DATA_DIR) return process.env.DATA_DIR;
${volumeSize > 0 ? `  // Hetzner automounts an attached Volume at /mnt/HC_Volume_<id>. It can lag
  // the first boot by a few seconds; never fall back to the root disk, or
  // the data splits across two places.
  for (let i = 0; i < 60; i++) {
    const v = existsSync("/mnt") ? readdirSync("/mnt").find((d) => d.startsWith("HC_Volume_")) : undefined;
    if (v) return join("/mnt", v, ${JSON.stringify(c.name)});
    await new Promise((r) => setTimeout(r, 1000));
  }
  console.error("no Hetzner Volume under /mnt after 60s; set DATA_DIR or check the Volume attachment");
  process.exit(1);` : `  return ${JSON.stringify(`/var/lib/${c.name}`)};`}
}

const child = spawn(bin, process.argv.slice(2), { stdio: "inherit", env: { ...process.env, DATA_DIR: await dataDir() } });
for (const sig of ["SIGTERM", "SIGINT", "SIGHUP"]) process.on(sig, () => child.kill(sig));
child.on("exit", (code, signal) => process.exit(code ?? (signal ? 1 : 0)));
`;
}

/**
 * Compile the box host and write its launcher. Returns the binary path.
 * `target` overrides the server's arch, e.g. your own OS to try the box locally.
 */
export async function buildBox(c: RustyBunsConfig, opts: { target?: string } = {}): Promise<string> {
  if (!c.targets.box) throw new Error("no targets.box in rustybuns.config.ts");
  if (c.targets.box.provider === "railway") return buildRailway(c);
  const { serverType } = boxDefaults(c.targets.box);
  await mkdir(BOX_DIR, { recursive: true });
  const out = await buildDesktop(c, { host: "box", target: opts.target ?? boxArch(serverType), outfile: `${BOX_DIR}/${c.name}` });
  await Bun.write(`${BOX_DIR}/launch.mjs`, boxLauncher(c));
  return out;
}

/** Bundle the box host for Railway and lay out its Docker context. Returns the context dir. */
export async function buildRailway(c: RustyBunsConfig): Promise<string> {
  // Rust cdylibs would need a linux build and a place in the image; not yet.
  if (existsSync("native/Cargo.toml") || c.targets.desktop?.native?.length)
    throw new Error("the Railway box does not carry native/ crates yet; use the Hetzner box for an app with Rust cdylibs");
  await rm(RAILWAY_DIR, { recursive: true, force: true });
  await mkdir(RAILWAY_DIR, { recursive: true });
  const out = await buildDesktop(c, { host: "box", noCompile: true, outdir: RAILWAY_DIR });
  const { assets, migrationDirs, mountDirs } = embeddedDirs(c);
  const dirs = [assets, ...migrationDirs, ...mountDirs].filter((p): p is string => !!p);
  const names = dirs.map((p) => basename(p));
  if (new Set(names).size !== names.length) throw new Error(`embedded directories must have distinct basenames: ${names.join(", ")}`);
  for (const dir of dirs) {
    if (!existsSync(dir)) throw new Error(`${dir} does not exist; the build should have produced it`);
    await cp(dir, join(RAILWAY_DIR, basename(dir)), { recursive: true });
  }
  await Bun.write(join(RAILWAY_DIR, "Dockerfile"), railwayDockerfile());
  return out;
}
