// experimental.wheel: who holds the keys to a stack's secrets.
//   agent  minted secrets live and die with the stack; 1Password via a service account
//   human  1Password via the app on your machine (Touch ID / passkey), never a token
// Minted secrets are Alchemy.Random in the generated stack (gen/alchemy.ts).
// The app's .env.schema (committed) names every secret and where it lives;
// varlock resolves it at plan/deploy and the values reach the stack as plain
// env, like .dev.vars. The same schema works anywhere varlock runs.

import type { RustyBunsConfig } from "./config.ts";

export const ENV_SCHEMA = ".env.schema";
/** Pinned: varlock's standalone binary only loads plugins at a fixed version. */
export const OP_PLUGIN = "@varlock/1password-plugin@2.0.4";

function secrets(c: RustyBunsConfig): { name: string; op?: string }[] {
  return Object.entries(c.bindings ?? {}).flatMap(([name, b]) => b.type === "secret" ? [{ name, op: b.op }] : []);
}

/** Refuse half-set configs before anything is generated. */
export function checkWheel(c: RustyBunsConfig): void {
  const wheel = c.experimental?.wheel;
  if (wheel !== undefined && wheel !== "agent" && wheel !== "human")
    throw new Error(`experimental.wheel is "${wheel}"; it takes "agent" or "human"`);
  for (const s of secrets(c)) {
    if (s.op === undefined) continue;
    if (!wheel) throw new Error(`secret ${s.name} has an op reference, which needs experimental.wheel ("agent" or "human")`);
    if (!s.op.startsWith("op://")) throw new Error(`secret ${s.name}: op should be a 1Password reference like "op://vault/item/field", not ${JSON.stringify(s.op)}`);
  }
}

/** Secrets the stack mints itself: wheel "agent", no op reference. */
export function mintedSecrets(c: RustyBunsConfig): string[] {
  return c.experimental?.wheel === "agent" ? secrets(c).filter((s) => !s.op).map((s) => s.name) : [];
}

/**
 * The app's committed .env.schema: every secret by name, where it comes from,
 * no values. Any machine, CI job or agent that clones the repo resolves the same
 * typed secrets from it, behind its own wheel. Null without experimental.wheel.
 */
export function generateEnvSchema(c: RustyBunsConfig): string | null {
  const wheel = c.experimental?.wheel;
  const all = secrets(c);
  if (!wheel || !all.length) return null;
  const minted = new Set(mintedSecrets(c));
  const vaulted = all.filter((s) => s.op);
  const lines = [
    `# GENERATED by rustybuns from rustybuns.config.ts (experimental.wheel: "${wheel}").`,
    `# Commit it: names and 1Password references only, never values. varlock resolves`,
    `# them at plan/deploy. Delete this header to own the file; rustybuns then uses it as-is.`,
  ];
  if (vaulted.length) lines.push(
    `# @plugin(${OP_PLUGIN})`,
    wheel === "human" ? `# @initOp(allowAppAuth=true)` : `# @initOp(token=$OP_TOKEN, allowAppAuth=false)`,
  );
  lines.push(`# ---`);
  if (vaulted.length && wheel === "agent") lines.push(``, `# A 1Password service account token scoped to this stack's vault.`, `# @type=opServiceAccountToken @sensitive @internal @required`, `OP_TOKEN=`);
  for (const s of all) {
    lines.push(``);
    if (s.op) lines.push(`# @sensitive @required`, `${s.name}=op(${s.op})`);
    else if (minted.has(s.name)) lines.push(`# ${s.name}: minted by the stack on create, gone on destroy (not resolved here).`);
    else lines.push(`# From the shell or .dev.vars.`, `# @sensitive`, `${s.name}=`);
  }
  return lines.join("\n") + "\n";
}

/** What running under a schema needs from the machine. */
export function schemaNeeds(text: string): { opToken: boolean; opCli: boolean } {
  return { opToken: text.includes("token=$OP_TOKEN"), opCli: text.includes("allowAppAuth=true") };
}
