// experimental.wheel: who holds the keys to a stack's secrets.
//   agent  minted secrets live and die with the stack; 1Password via a service account
//   human  1Password via the app on your machine (Touch ID / passkey), never a token
// Minted secrets are Alchemy.Random in the generated stack (gen/alchemy.ts).
// 1Password secrets are fetched by varlock at plan/deploy time from a generated
// .rustybuns/.env.schema, then reach the stack as plain env, like .dev.vars.

import type { RustyBunsConfig } from "./config.ts";

export const ENV_SCHEMA = ".rustybuns/.env.schema";
/** Pinned: varlock's standalone binary only loads plugins at a fixed version. */
export const OP_PLUGIN = "@varlock/1password-plugin@2.0.4";

function secrets(c: RustyBunsConfig): { name: string; op?: string }[] {
  return Object.entries(c.bindings ?? {}).flatMap(([name, b]) => b.type === "secret" ? [{ name, op: b.op }] : []);
}

/** Refuse half-set configs before anything is generated. */
export function checkWheel(c: RustyBunsConfig): void {
  const wheel = c.experimental?.wheel;
  if (wheel !== undefined && wheel !== "agent" && wheel !== "human")
    throw new Error(`experimental.wheel is "${wheel}"; it takes "agent" or "human"`);
  for (const s of secrets(c)) {
    if (s.op === undefined) continue;
    if (!wheel) throw new Error(`secret ${s.name} has an op reference, which needs experimental.wheel ("agent" or "human")`);
    if (!s.op.startsWith("op://")) throw new Error(`secret ${s.name}: op should be a 1Password reference like "op://vault/item/field", not ${JSON.stringify(s.op)}`);
  }
}

/** Secrets the stack mints itself: wheel "agent", no op reference. */
export function mintedSecrets(c: RustyBunsConfig): string[] {
  return c.experimental?.wheel === "agent" ? secrets(c).filter((s) => !s.op).map((s) => s.name) : [];
}

/** The varlock schema for the op secrets, or null when there are none. */
export function generateEnvSchema(c: RustyBunsConfig): string | null {
  const wheel = c.experimental?.wheel;
  const vaulted = secrets(c).filter((s) => s.op);
  if (!wheel || !vaulted.length) return null;
  const lines = [
    `# GENERATED by rustybuns from rustybuns.config.ts (experimental.wheel: "${wheel}").`,
    `# Names and 1Password references only; values are fetched by varlock at plan/deploy.`,
    `# @plugin(${OP_PLUGIN})`,
    wheel === "human"
      ? `# @initOp(allowAppAuth=true)`
      : `# @initOp(token=$OP_TOKEN, allowAppAuth=false)`,
    `# ---`,
  ];
  if (wheel === "agent") lines.push(`# A service account token scoped to this stack's vault.`, `# @type=opServiceAccountToken @sensitive @internal @required`, `OP_TOKEN=`);
  for (const s of vaulted) lines.push(`# @sensitive @required`, `${s.name}=op(${s.op})`);
  return lines.join("\n") + "\n";
}
